# This file was generated by GoReleaser. DO NOT EDIT.
class Abwhose < Formula
  desc "The simplest way to find how to report abusive domains."
  homepage "https://github.com/bradleyjkemp/abwhose"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradleyjkemp/abwhose/releases/download/v0.1.3/abwhose_0.1.3_macOS_amd64.zip"
    sha256 "4b3bfd16c3637334adf346096172724f458b516654c3cf736c044f2e9cb44e53"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bradleyjkemp/abwhose/releases/download/v0.1.3/abwhose_0.1.3_Linux_amd64.zip"
      sha256 "32193e8bae8cb952532cb16a76c48cf66ed594bddfc6c15ddce39da6601aa99d"
    end
  end

  def install
    bin.install "abwhose"
  end
end
