# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abwhose < Formula
  desc "The simplest way to find how to report abusive domains."
  homepage "https://github.com/bradleyjkemp/abwhose"
  version "0.1.13"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bradleyjkemp/abwhose/releases/download/v0.1.13/abwhose_0.1.13_macOS_amd64.zip"
    sha256 "ebc76eec6236700018c9dcdfd236e48ad9d15131b7c0ad4d43bbc3d10f918515"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bradleyjkemp/abwhose/releases/download/v0.1.13/abwhose_0.1.13_Linux_amd64.zip"
    sha256 "08c28db548e5f9a21894bb5d584e2f950e6d2ad6d2af53c08ea727603bf0570d"
  end

  def install
    bin.install "abwhose"
  end
end
