# This file was generated by GoReleaser. DO NOT EDIT.
class GrpcTools < Formula
  desc "A suite of gRPC debugging tools. Like Fiddler/Charles but for gRPC."
  homepage "https://github.com/bradleyjkemp/grpc-tools"
  version "0.1.0"

  if OS.mac?
    url "https://github.com/bradleyjkemp/grpc-tools/releases/download/v0.1.0/grpc-tools_0.1.0_macOS_amd64.zip"
    sha256 "fadbcb85d88a827263c277c317a9e8c2da5be709bc7097453334e6a5a65b467c"
  elsif OS.linux?
    url "https://github.com/bradleyjkemp/grpc-tools/releases/download/v0.1.0/grpc-tools_0.1.0_Linux_amd64.zip"
    sha256 "d658d71512d4bdc155673431614e6852d1ff744b6def4f4630217e9534a11675"
  end

  def install
    bin.install "grpc-dump"
    bin.install "grpc-fixture"
    bin.install "grpc-replay"
    bin.install "grpc-view"
  end
end
