# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sigmafmt < Formula
  desc "An opinionated formatter/linter for Sigma rules"
  homepage "https://github.com/bradleyjkemp/sigmafmt"
  version "0.1.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bradleyjkemp/sigmafmt/releases/download/v0.1.4/sigmafmt_0.1.4_macOS_amd64.zip"
    sha256 "379e894dc08a2aa0c735c022123fe8e1d202bf7b5249625f0609dddc961a4acd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bradleyjkemp/sigmafmt/releases/download/v0.1.4/sigmafmt_0.1.4_Linux_amd64.zip"
    sha256 "bc4d906b0a16326c33ac65dbd5e5a3d2f10a387ae628e55ffd0d9cff78595776"
  end

  def install
    bin.install "sigmafmt"
  end
end
