# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SigmaGo < Formula
  desc "A Go implementation and parser of Sigma rules."
  homepage "https://github.com/bradleyjkemp/sigma-go"
  version "0.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradleyjkemp/sigma-go/releases/download/v0.2.2/sigma-go_0.2.2_macOS_amd64.zip"
    sha256 "426072e0c9fd24f4714db4a3706d54ebf0ba8f059d47e3809d21aad081011aaf"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bradleyjkemp/sigma-go/releases/download/v0.2.2/sigma-go_0.2.2_Linux_amd64.zip"
    sha256 "d0406f9c9e2d0b7742dd9ca7564ad187a2303cd0dc22903f84f79f1e2ca64b8d"
  end

  def install
    bin.install "sigmac"
  end
end
