# This file was generated by GoReleaser. DO NOT EDIT.
class Sigmafmt < Formula
  desc "An opinionated formatter/linter for Sigma rules"
  homepage "https://github.com/bradleyjkemp/sigmafmt"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradleyjkemp/sigmafmt/releases/download/v0.1.0/sigmafmt_0.1.0_macOS_amd64.zip"
    sha256 "b416101be22a7aaf29452037a6a70a9045fdd1a4dd39fce0f60600fc3ab47992"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bradleyjkemp/sigmafmt/releases/download/v0.1.0/sigmafmt_0.1.0_Linux_amd64.zip"
      sha256 "3807c3b08cd0c486adbb63c28a8484c0b9d42d439895aba35ff4642ac305d2f9"
    end
  end

  def install
    bin.install "sigmafmt"
  end
end
