# This file was generated by GoReleaser. DO NOT EDIT.
class SigmaTest < Formula
  desc "A test case runner for Sigma rules."
  homepage "https://github.com/bradleyjkemp/sigma-test"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradleyjkemp/sigma-test/releases/download/v0.0.1/sigma-test_0.0.1_macOS_amd64.zip"
    sha256 "c30d6b9d49760e4560a95408e5c974bdba00c37623bfb7461542bc13749433ec"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bradleyjkemp/sigma-test/releases/download/v0.0.1/sigma-test_0.0.1_Linux_amd64.zip"
      sha256 "77b7353635420fef5a69c4209f4e886edede7f6b59b97a75a2309662ae0be98d"
    end
  end

  def install
    bin.install "sigma-test"
  end
end
