# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SigmaGo < Formula
  desc "A Go implementation and parser of Sigma rules."
  homepage "https://github.com/bradleyjkemp/sigma-go"
  version "0.2.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradleyjkemp/sigma-go/releases/download/v0.2.3/sigma-go_0.2.3_macOS_amd64.zip"
    sha256 "d50a30598db44ca0abd45d58d35d96a5d4d820eefc88e236817a8f9b1daa502b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bradleyjkemp/sigma-go/releases/download/v0.2.3/sigma-go_0.2.3_Linux_amd64.zip"
    sha256 "5ab725603a94c478a3cb2eda7ae1d45d27a2de4d081fdc7cdf6a66f578dbc8b5"
  end

  def install
    bin.install "sigmac"
  end
end
