# This file was generated by GoReleaser. DO NOT EDIT.
class Sigmafmt < Formula
  desc "An opinionated formatter/linter for Sigma rules"
  homepage "https://github.com/bradleyjkemp/sigmafmt"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradleyjkemp/sigmafmt/releases/download/v0.1.3/sigmafmt_0.1.3_macOS_amd64.zip"
    sha256 "0dfe468204803a51620e2ca1e5af550eac338f47738a6395c49e7595f1566993"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bradleyjkemp/sigmafmt/releases/download/v0.1.3/sigmafmt_0.1.3_Linux_amd64.zip"
    sha256 "07c8b4f76e61fc710935fffc73e42bcf22183161434c0f7ed99076cd348fbec4"
  end

  def install
    bin.install "sigmafmt"
  end
end
